services:
  redis:
    image: redis/redis-stack
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"   # RedisInsight
    volumes:
      - redis-data:/data

volumes:
  redis-data:
